name: Wails Build

on:
  push:
    tags:
      - '*' # Trigger on tag pushes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.8'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.16.0'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/cmd/wails@v1.16.9

      - name: Build for Linux
        run: wails build -platform linux/amd64

      - name: Build for Windows
        run: wails build -platform windows/amd64

      - name: Build for macOS
        run: wails build -platform darwin/amd64
